name: GenerateSnake
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-snakes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: "github-actions[bot]"
          gif_out_path: ./img/snake.gif
          svg_out_path: ./img/snake.svg
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9.1.4
        with:
          branch: master  
          message: ':rocket: Update'
